# Generated by Django 3.0.6 on 2023-08-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('Change Pending', 'Change Pending'), ('Delete Pending', 'Delete Pending'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=50),
        ),
    ]
